// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghaezdgqzagemjbsvdfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoYWV6ZGdxemFnZW1qYnN2ZGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzU4MTgsImV4cCI6MjA3NDM1MTgxOH0.OVDrxV4sG04bqntK_SJx-4vvjJ0AVQEkva3pK7ep5uY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});